[web]
web-01 ansible_host=192.168.56.10

[app]
app-01 ansible_host=192.168.56.13

[db]
db-01 ansible_host=192.168.56.12

[logs]
logs-01 ansible_host=192.168.56.11

[workers]
worker-01 ansible_host=192.168.56.14

[infra:children]
web
app
db
logs
workers

[all:vars]
ansible_user=ubuntu